[package]
name = "lodestone"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.13"
rfd = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zip = "0.6"
toml = "0.8"
